//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Data.Mapping.EntityViewGenerationAttribute(typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySetsDEA597111302F1C12C1FF41714D4A73F73AA5A3ACFF796B5F0B9EBA7CC75B824))]

namespace Edm_EntityMappingGeneratedViews
{
    
    
    /// <Summary>
    /// The type contains views for EntitySets and AssociationSets that were generated at design time.
    /// </Summary>
    public sealed class ViewsForBaseEntitySetsDEA597111302F1C12C1FF41714D4A73F73AA5A3ACFF796B5F0B9EBA7CC75B824 : System.Data.Mapping.EntityViewContainer
    {
        
        /// <Summary>
        /// The constructor stores the views for the extents and also the hash values generated based on the metadata and mapping closure and views.
        /// </Summary>
        public ViewsForBaseEntitySetsDEA597111302F1C12C1FF41714D4A73F73AA5A3ACFF796B5F0B9EBA7CC75B824()
        {
            this.EdmEntityContainerName = "EmplSampleEntities";
            this.StoreEntityContainerName = "EmplSampleModelStoreContainer";
            this.HashOverMappingClosure = "0eaad76f96cbd2c2f0cc26c825d33a48dc0e6f15852aa1d5da72cdea740bce67";
            this.HashOverAllExtentViews = "9cd733526515be90972fb28b1b9c8c64290e187ff1fb77aa3a25033793038d67";
            this.ViewCount = 4;
        }
        
        /// <Summary>
        /// The method returns the view for the index given.
        /// </Summary>
        protected override System.Collections.Generic.KeyValuePair<string, string> GetViewAt(int index)
        {
            if ((index == 0))
            {
                return GetView0();
            }
            if ((index == 1))
            {
                return GetView1();
            }
            if ((index == 2))
            {
                return GetView2();
            }
            if ((index == 3))
            {
                return GetView3();
            }
            throw new System.IndexOutOfRangeException();
        }
        
        /// <Summary>
        /// return view for EmplSampleModelStoreContainer.EmployeeDetails
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView0()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("EmplSampleModelStoreContainer.EmployeeDetails", @"
    SELECT VALUE -- Constructing EmployeeDetails
        [EmplSampleModel.Store.EmployeeDetails](T1.EmployeeDetails_EmployeeID, T1.EmployeeDetails_FirstName, T1.EmployeeDetails_Surname, T1.EmployeeDetails_Address, T1.EmployeeDetails_Phone)
    FROM (
        SELECT 
            T.EmployeeID AS EmployeeDetails_EmployeeID, 
            T.FirstName AS EmployeeDetails_FirstName, 
            T.Surname AS EmployeeDetails_Surname, 
            T.Address AS EmployeeDetails_Address, 
            T.Phone AS EmployeeDetails_Phone, 
            True AS _from0
        FROM EmplSampleEntities.EmployeeDetails AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for EmplSampleEntities.EmployeeDetails
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView1()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("EmplSampleEntities.EmployeeDetails", @"
    SELECT VALUE -- Constructing EmployeeDetails
        [EmplSampleModel.EmployeeDetail](T1.EmployeeDetail_EmployeeID, T1.EmployeeDetail_FirstName, T1.EmployeeDetail_Surname, T1.EmployeeDetail_Address, T1.EmployeeDetail_Phone)
    FROM (
        SELECT 
            T.EmployeeID AS EmployeeDetail_EmployeeID, 
            T.FirstName AS EmployeeDetail_FirstName, 
            T.Surname AS EmployeeDetail_Surname, 
            T.Address AS EmployeeDetail_Address, 
            T.Phone AS EmployeeDetail_Phone, 
            True AS _from0
        FROM EmplSampleModelStoreContainer.EmployeeDetails AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for EmplSampleModelStoreContainer.trackinghours
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView2()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("EmplSampleModelStoreContainer.trackinghours", @"
    SELECT VALUE -- Constructing trackinghours
        [EmplSampleModel.Store.trackinghours](T1.trackinghours_EmployeeID, T1.trackinghours_Surname, T1.trackinghours_Arrival, T1.trackinghours_Departure)
    FROM (
        SELECT 
            T.EmployeeID AS trackinghours_EmployeeID, 
            T.Surname AS trackinghours_Surname, 
            T.Arrival AS trackinghours_Arrival, 
            T.Departure AS trackinghours_Departure, 
            True AS _from0
        FROM EmplSampleEntities.trackinghours AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for EmplSampleEntities.trackinghours
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView3()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("EmplSampleEntities.trackinghours", @"
    SELECT VALUE -- Constructing trackinghours
        [EmplSampleModel.trackinghour](T1.trackinghour_EmployeeID, T1.trackinghour_Surname, T1.trackinghour_Arrival, T1.trackinghour_Departure)
    FROM (
        SELECT 
            T.EmployeeID AS trackinghour_EmployeeID, 
            T.Surname AS trackinghour_Surname, 
            T.Arrival AS trackinghour_Arrival, 
            T.Departure AS trackinghour_Departure, 
            True AS _from0
        FROM EmplSampleModelStoreContainer.trackinghours AS T
    ) AS T1");
        }
    }
}
